apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqtt.fullname" . }}-config
  labels:
    {{- include "mqtt.labels" . | nindent 4 }}
data:
  mosquitto-no-auth.conf: |
    listener {{ .Values.service.port }}
    allow_anonymous {{ .Values.config.allowAnonymous }} 