apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt.fullname" . }}
  labels:
    {{- include "mqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "mqtt.selectorLabels" . | nindent 4 }} 