apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frigate.fullname" . }}-config
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
data:
  config.yml: |
    mqtt:
      host: {{ .Values.mqtt.host }}
      port: {{ .Values.mqtt.port }}
      user: {{ .Values.mqtt.user }}
      password: {{ .Values.mqtt.password }}
    database:
      path: /data/frigate.db
    cameras:
      {{- toYaml .Values.cameras | nindent 6 }} 