{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "frigate.fullname" . }}-recordings
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.recordings.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "frigate.fullname" . }}-cache
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "frigate.fullname" . }}-database
  labels:
    {{- include "frigate.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.database.size }}
{{- end }} 