replicaCount: 1

image:
  repository: eclipse-mosquitto
  tag: "2"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 1883

config:
  allowAnonymous: true
  persistence:
    enabled: false
    size: 1Gi 